version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
   

    env_file:
      - .env
      
    depends_on:
      - db
    networks:
      - blog_network     

  db:
    image: postgres:latest
   
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blog_network
      
networks:
  blog_network:
    driver: bridge

volumes:
  pgdata:

   
